import { Product } from './store'

export const categories = [
  { id: 'pottery', name: 'Pottery & Ceramics', nameFr: 'Poterie & Céramiques', nameAr: 'الفخار والسيراميك' },
  { id: 'leather', name: 'Leather Goods', nameFr: 'Maroquinerie', nameAr: 'المصنوعات الجلدية' },
  { id: 'textiles', name: 'Traditional Textiles', nameFr: 'Textiles Traditionnels', nameAr: 'المنسوجات التقليدية' },
  { id: 'lighting', name: 'Lighting', nameFr: 'Luminaires', nameAr: 'الإضاءة' },
  { id: 'glassware', name: 'Glassware & Teapots', nameFr: 'Verrerie & Théières', nameAr: 'الزجاجيات وأباريق الشاي' },
]

export const products: Product[] = [
  // Pottery & Ceramics
  {
    id: 'pottery-1',
    name: 'Fès Blue Ceramic Bowl',
    nameFr: 'Bol en Céramique Bleu de Fès',
    nameAr: 'وعاء سيراميك أزرق فاسي',
    price: 85,
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&q=80',
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&q=80',
    ],
    category: 'pottery',
    description: 'Hand-painted ceramic bowl featuring traditional Fès blue patterns. Each piece is unique, crafted by skilled artisans in the medina.',
    descriptionFr: 'Bol en céramique peint à la main avec des motifs bleus traditionnels de Fès. Chaque pièce est unique, fabriquée par des artisans qualifiés dans la médina.',
    descriptionAr: 'وعاء سيراميك مرسوم يدوياً بأنماط فاس الزرقاء التقليدية. كل قطعة فريدة من نوعها، مصنوعة بواسطة حرفيين ماهرين في المدينة القديمة.',
    colors: ['Blue', 'Green', 'Terracotta'],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 'pottery-2',
    name: 'Zellige Mosaic Plate',
    nameFr: 'Assiette Mosaïque Zellige',
    nameAr: 'طبق فسيفساء زليج',
    price: 120,
    image: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&q=80',
    ],
    category: 'pottery',
    description: 'Stunning decorative plate inspired by the iconic zellige tilework of Moroccan architecture.',
    descriptionFr: 'Assiette décorative époustouflante inspirée du célèbre carrelage zellige de l\'architecture marocaine.',
    descriptionAr: 'طبق ديكوري مذهل مستوحى من فن الزليج الأيقوني في العمارة المغربية.',
    colors: ['Multicolor'],
    inStock: true,
    featured: true,
  },
  {
    id: 'pottery-3',
    name: 'Traditional Tagine Pot',
    nameFr: 'Tajine Traditionnel',
    nameAr: 'طاجين تقليدي',
    price: 95,
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=600&q=80',
    category: 'pottery',
    description: 'Authentic cooking tagine with hand-painted geometric patterns. Perfect for slow-cooked Moroccan dishes.',
    colors: ['Natural', 'Blue', 'Green'],
    inStock: true,
    bestSeller: true,
  },
  // Leather Goods
  {
    id: 'leather-1',
    name: 'Artisan Leather Tote Bag',
    nameFr: 'Sac Fourre-tout en Cuir Artisanal',
    nameAr: 'حقيبة جلد يدوية الصنع',
    price: 180,
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80',
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&q=80',
    ],
    category: 'leather',
    description: 'Handcrafted from premium Moroccan leather, tanned using traditional methods in the famous Fès tanneries.',
    colors: ['Tan', 'Brown', 'Black'],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 'leather-2',
    name: 'Embossed Leather Wallet',
    nameFr: 'Portefeuille en Cuir Gaufré',
    nameAr: 'محفظة جلد منقوشة',
    price: 65,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&q=80',
    category: 'leather',
    description: 'Elegant wallet with traditional Moroccan embossing. Multiple card slots and bill compartment.',
    colors: ['Brown', 'Tan', 'Black'],
    inStock: true,
  },
  {
    id: 'leather-3',
    name: 'Moroccan Leather Belt',
    nameFr: 'Ceinture en Cuir Marocain',
    nameAr: 'حزام جلد مغربي',
    price: 55,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    category: 'leather',
    description: 'Classic leather belt with brass buckle, featuring subtle traditional patterns.',
    colors: ['Brown', 'Black'],
    inStock: true,
  },
  // Traditional Textiles
  {
    id: 'textiles-1',
    name: 'Berber Wool Rug',
    nameFr: 'Tapis en Laine Berbère',
    nameAr: 'سجادة صوف أمازيغية',
    price: 450,
    image: 'https://images.unsplash.com/photo-1600166898405-da9535204843?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1600166898405-da9535204843?w=600&q=80',
    ],
    category: 'textiles',
    description: 'Hand-woven by Berber women in the Atlas Mountains. Each rug tells a unique story through its patterns.',
    colors: ['Natural', 'Black & White', 'Colorful'],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 'textiles-2',
    name: 'Unisex Wool Jacket',
    nameFr: 'Veste en Laine Unisexe',
    nameAr: 'جاكيت صوف للجنسين',
    price: 220,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80',
    category: 'textiles',
    description: 'Traditional Moroccan jacket made from finest wool with intricate embroidery.',
    colors: ['Cream', 'Navy', 'Burgundy'],
    inStock: true,
  },
  {
    id: 'textiles-3',
    name: 'Hand-Embroidered Cushion',
    nameFr: 'Coussin Brodé à la Main',
    nameAr: 'وسادة مطرزة يدوياً',
    price: 75,
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80',
    category: 'textiles',
    description: 'Luxurious cushion cover with traditional Moroccan embroidery patterns.',
    colors: ['Gold', 'Silver', 'Copper'],
    inStock: true,
  },
  // Lighting
  {
    id: 'lighting-1',
    name: 'Brass Moroccan Lantern',
    nameFr: 'Lanterne Marocaine en Laiton',
    nameAr: 'فانوس مغربي نحاسي',
    price: 165,
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&q=80',
    ],
    category: 'lighting',
    description: 'Intricately pierced brass lantern casting beautiful shadow patterns. Creates magical ambient lighting.',
    colors: ['Brass', 'Antique Bronze'],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 'lighting-2',
    name: 'Colorful Glass Pendant Lamp',
    nameFr: 'Suspension en Verre Coloré',
    nameAr: 'مصباح معلق زجاجي ملون',
    price: 195,
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&q=80',
    category: 'lighting',
    description: 'Handcrafted pendant lamp with colored glass panels, perfect for creating a warm atmosphere.',
    colors: ['Multicolor', 'Amber', 'Blue'],
    inStock: true,
  },
  {
    id: 'lighting-3',
    name: 'Table Lamp with Henna Shade',
    nameFr: 'Lampe de Table avec Abat-jour au Henné',
    nameAr: 'مصباح طاولة بغطاء حناء',
    price: 125,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80',
    category: 'lighting',
    description: 'Unique table lamp featuring a genuine goatskin shade painted with traditional henna designs.',
    colors: ['Natural'],
    inStock: true,
  },
  // Glassware & Teapots
  {
    id: 'glassware-1',
    name: 'Traditional Moroccan Teapot',
    nameFr: 'Théière Marocaine Traditionnelle',
    nameAr: 'إبريق شاي مغربي تقليدي',
    price: 85,
    image: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=600&q=80',
    ],
    category: 'glassware',
    description: 'Authentic silver-plated teapot, essential for the traditional Moroccan mint tea ceremony.',
    colors: ['Silver', 'Gold'],
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    id: 'glassware-2',
    name: 'Decorated Tea Glass Set',
    nameFr: 'Ensemble de Verres à Thé Décorés',
    nameAr: 'طقم كؤوس شاي مزخرفة',
    price: 45,
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&q=80',
    category: 'glassware',
    description: 'Set of 6 hand-painted tea glasses with gold trim. Perfect for serving traditional mint tea.',
    colors: ['Gold & Blue', 'Gold & Green', 'Gold & Red'],
    inStock: true,
  },
  {
    id: 'glassware-3',
    name: 'Blown Glass Vase',
    nameFr: 'Vase en Verre Soufflé',
    nameAr: 'مزهرية زجاج منفوخ',
    price: 110,
    image: 'https://images.unsplash.com/photo-1481277542470-605612bd2d61?w=600&q=80',
    category: 'glassware',
    description: 'Beautiful hand-blown glass vase in traditional Moroccan colors.',
    colors: ['Blue', 'Amber', 'Green'],
    inStock: false,
  },
]

export const getProductById = (id: string) => products.find((p) => p.id === id)
export const getProductsByCategory = (category: string) => products.filter((p) => p.category === category)
export const getFeaturedProducts = () => products.filter((p) => p.featured)
export const getBestSellers = () => products.filter((p) => p.bestSeller)
